// PDF Service - Generate PDFs using Puppeteer
// Creates professionally formatted PDF documents from MCQ data

const isVercel = process.env.VERCEL === '1';
let puppeteer;
let chromium;

if (isVercel) {
    puppeteer = require('puppeteer-core');
    chromium = require('@sparticuz/chromium-min');
} else {
    puppeteer = require('puppeteer');
}

// Generate HTML template for PDF
function generatePDFHTML(mcqs, title, includeExplanation) {
    const currentDate = new Date().toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'long',
        day: 'numeric'
    });

    return `
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>${title}</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }

        body {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            line-height: 1.6;
            color: #333;
            padding: 40px;
            background: white;
        }

        .header {
            text-align: center;
            margin-bottom: 40px;
            padding-bottom: 20px;
            border-bottom: 3px solid #6366f1;
        }

        .header h1 {
            color: #6366f1;
            font-size: 32px;
            margin-bottom: 10px;
        }

        .header .subtitle {
            color: #666;
            font-size: 14px;
        }

        .mcq-container {
            margin-bottom: 30px;
            page-break-inside: avoid;
        }

        .question {
            font-size: 16px;
            font-weight: 600;
            color: #1f2937;
            margin-bottom: 15px;
            line-height: 1.5;
        }

        .options {
            margin-left: 20px;
            margin-bottom: 15px;
        }

        .option {
            margin-bottom: 8px;
            font-size: 14px;
            color: #4b5563;
            line-height: 1.4;
        }

        .answer {
            background: #f0fdf4;
            border-left: 4px solid #22c55e;
            padding: 10px 15px;
            margin-bottom: 10px;
            font-weight: 600;
            color: #166534;
            font-size: 14px;
        }

        .explanation {
            background: #f8fafc;
            border-left: 4px solid #6366f1;
            padding: 12px 15px;
            margin-top: 10px;
            font-size: 13px;
            color: #475569;
            font-style: italic;
            line-height: 1.5;
        }

        .explanation strong {
            color: #1e293b;
            font-style: normal;
        }

        .divider {
            height: 1px;
            background: #e5e7eb;
            margin: 25px 0;
        }

        .footer {
            margin-top: 50px;
            text-align: center;
            font-size: 12px;
            color: #9ca3af;
            padding-top: 20px;
            border-top: 1px solid #e5e7eb;
        }

        @media print {
            body {
                padding: 20px;
            }
            
            .mcq-container {
                page-break-inside: avoid;
            }
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>${title}</h1>
        <p class="subtitle">Generated on ${currentDate}</p>
        <p class="subtitle">Total Questions: ${mcqs.length}</p>
    </div>

    ${mcqs.map((mcq, index) => {
        const opt = mcq.options || {};
        return `
        <div class="mcq-container">
            <div class="question">Q${index + 1}. ${mcq.question || 'No question provided'}</div>
            <div class="options">
                <div class="option">A. ${opt.A || 'N/A'}</div>
                <div class="option">B. ${opt.B || 'N/A'}</div>
                <div class="option">C. ${opt.C || 'N/A'}</div>
                <div class="option">D. ${opt.D || 'N/A'}</div>
            </div>
            <div class="answer">✓ Correct Answer: ${mcq.correctAnswer || 'Not specified'}</div>
            ${includeExplanation && mcq.explanation ? `
                <div class="explanation">
                    <strong>Explanation:</strong> ${mcq.explanation}
                </div>
            ` : ''}
            ${index < mcqs.length - 1 ? '<div class="divider"></div>' : ''}
        </div>
    `;
    }).join('')}

    <div class="footer">
        <p>Generated by MCQ Engine - AI-Powered Assessment Tool</p>
        <p>© ${new Date().getFullYear()} - All Rights Reserved</p>
    </div>
</body>
</html>
    `;
}

// Generate PDF from MCQ data
async function generatePDF(mcqs, title = 'MCQ Assessment', includeExplanation = true) {
    let browser;

    try {
        // Launch browser based on environment
        if (isVercel) {
            browser = await puppeteer.launch({
                args: chromium.args,
                defaultViewport: chromium.defaultViewport,
                executablePath: await chromium.executablePath(),
                headless: chromium.headless,
                ignoreHTTPSErrors: true,
            });
        } else {
            browser = await puppeteer.launch({
                headless: 'new',
                args: [
                    '--no-sandbox',
                    '--disable-setuid-sandbox',
                    '--disable-dev-shm-usage',
                    '--disable-accelerated-2d-canvas',
                    '--no-first-run',
                    '--no-zygote',
                    '--single-process',
                    '--disable-gpu'
                ]
            });
        }

        const page = await browser.newPage();

        // Generate HTML content
        const htmlContent = generatePDFHTML(mcqs, title, includeExplanation);

        // Set content
        await page.setContent(htmlContent, {
            waitUntil: 'networkidle0'
        });

        // Generate PDF
        const pdfBuffer = await page.pdf({
            format: 'A4',
            printBackground: true,
            margin: {
                top: '20mm',
                right: '15mm',
                bottom: '20mm',
                left: '15mm'
            }
        });

        await browser.close();

        return pdfBuffer;

    } catch (error) {
        if (browser) {
            await browser.close();
        }
        console.error('Error generating PDF:', error);
        throw new Error(`Failed to generate PDF: ${error.message}`);
    }
}

module.exports = {
    generatePDF
};
